# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04\x64\x61ta\"\xd6\x02\n\x04\x44\x61ta\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\t\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\t\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\t\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\t\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\t\x12\x0e\n\x06\x66ield9\x18\t \x01(\x05\x12\x0f\n\x07\x66ield10\x18\n \x01(\t\x12!\n\x07\x66ield15\x18\x0f \x01(\x0b\x32\x10.data.SubField15\x12\x0f\n\x07\x66ield16\x18\x10 \x01(\t\x12\x0f\n\x07\x66ield19\x18\x13 \x01(\t\x12!\n\x07\x66ield20\x18\x14 \x01(\x0b\x32\x10.data.SubField20\x12\x0f\n\x07\x66ield21\x18\x15 \x01(\x03\x12\x0f\n\x07\x66ield22\x18\x16 \x01(\x0c\x12\x0f\n\x07\x66ield23\x18\x17 \x01(\x0c\x12\x0f\n\x07\x66ield24\x18\x18 \x01(\t\x12!\n\x07\x66ield25\x18\x19 \x01(\x0b\x32\x10.data.SubField25\"\x1c\n\nSubField15\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\"\x1c\n\nSubField20\x12\x0e\n\x06\x66ield6\x18\x06 \x01(\x05\"<\n\nSubField25\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=21
  _globals['_DATA']._serialized_end=363
  _globals['_SUBFIELD15']._serialized_start=365
  _globals['_SUBFIELD15']._serialized_end=393
  _globals['_SUBFIELD20']._serialized_start=395
  _globals['_SUBFIELD20']._serialized_end=423
  _globals['_SUBFIELD25']._serialized_start=425
  _globals['_SUBFIELD25']._serialized_end=485
# @@protoc_insertion_point(module_scope)
